// Generated by scripts/build-shotlist.mjs from docs/shot-list.json. Do not edit by hand.
export const SHOT_META: Record<string, { mode: "day" | "night"; ratio: string }> = {
  "hero-day": {
    "mode": "day",
    "ratio": "16:9"
  },
  "hero-night": {
    "mode": "night",
    "ratio": "16:9"
  },
  "interior-day": {
    "mode": "day",
    "ratio": "16:9"
  },
  "interior-night": {
    "mode": "night",
    "ratio": "16:9"
  },
  "detail-window-light": {
    "mode": "day",
    "ratio": "16:9"
  },
  "zone-window": {
    "mode": "day",
    "ratio": "4:5"
  },
  "zone-sofa": {
    "mode": "night",
    "ratio": "4:5"
  },
  "zone-bar": {
    "mode": "day",
    "ratio": "4:5"
  },
  "zone-terrace": {
    "mode": "day",
    "ratio": "4:5"
  },
  "zone-communal": {
    "mode": "night",
    "ratio": "4:5"
  },
  "process-espresso": {
    "mode": "night",
    "ratio": "3:2"
  },
  "process-latte-art": {
    "mode": "day",
    "ratio": "3:2"
  },
  "process-pour-over": {
    "mode": "day",
    "ratio": "3:2"
  },
  "process-roast": {
    "mode": "night",
    "ratio": "3:2"
  },
  "event-vinyl": {
    "mode": "night",
    "ratio": "3:2"
  },
  "event-wine-tasting": {
    "mode": "night",
    "ratio": "3:2"
  },
  "event-cupping": {
    "mode": "day",
    "ratio": "3:2"
  },
  "event-latte-class": {
    "mode": "day",
    "ratio": "3:2"
  },
  "menu-espresso": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-cappuccino": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-flat-white": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-raf": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-v60": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-espresso-tonic": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-sea-buckthorn-tea": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-syrniki": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-eggs-benedict": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-shakshuka": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-ricotta-toast": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-porridge": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-croissant": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-cardamom-bun": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-pumpkin-soup": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-borscht": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-beet-salad": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-pasta": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-burrata": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-tartare": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-cheese-board": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-duck": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-zander": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-espresso-martini": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-basque-cheesecake": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-medovik": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-latte": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-cacao": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-matcha": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-granola": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-canele": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-focaccia": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-salmon-bowl": {
    "mode": "day",
    "ratio": "4:5"
  },
  "menu-bruschetta": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-scallop-crudo": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-risotto": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-negroni": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-spritz": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-tiramisu": {
    "mode": "night",
    "ratio": "4:5"
  },
  "menu-fondant": {
    "mode": "night",
    "ratio": "4:5"
  },
  "detail-candle": {
    "mode": "night",
    "ratio": "4:5"
  },
  "detail-steam": {
    "mode": "night",
    "ratio": "4:5"
  },
  "detail-hands-cup": {
    "mode": "day",
    "ratio": "4:5"
  },
  "detail-bakery": {
    "mode": "day",
    "ratio": "3:2"
  },
  "facade-evening": {
    "mode": "night",
    "ratio": "4:5"
  },
  "wine-pour": {
    "mode": "night",
    "ratio": "4:5"
  },
  "hero-day-mobile": {
    "mode": "day",
    "ratio": "9:16"
  },
  "hero-night-mobile": {
    "mode": "night",
    "ratio": "9:16"
  }
};
